nname: Salvando Artifacts

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Relatório gerado" > relatorio.txt
      - uses: actions/upload-artifact@v3
        with:
          name: relatorio
          path: relatorio.txt

