name: Workflow manual

on:
  workflow_dispatch:

jobs:
  checkout-code:
    runs-on: ubuntu-latest

    steps:
    - name: Rodando um job manualmente
      run: echo "Este workflow foi iniciado maualmente"
