name: Usando Action Pronta - Checkout

on:
  push:
    branches:
      - main

jobs:
  checkout-code:
    runs-on: ubuntu-latest

    steps:
    - name: Usando o actions/checkout
      uses: actions/checkout@v4

    - name: Listando arquivos do repositório
      run: ls -la
